# Generated by Django 5.1 on 2024-08-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('Course', models.CharField(max_length=150)),
                ('Message', models.TextField()),
            ],
        ),
    ]
